# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

# platform :ios, '10.0'

target 'HFTP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HFTP
  pod 'SideMenu', '~> 6.0'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
pod 'CalendarKit'	
pod 'PhoneNumberKit', '~> 3.1'

end
